### PR TITLE
Sys class metrics2

### PR DESCRIPTION
**Pull request by Katy-katy**

### CODE REVIEW

**Comment by Katy-katy** [comment]
@lensonp , I am going to review it one more time  - I will let you know when it is ready

**Comment by Katy-katy** [comment]
@lensonp Now, I think it is ready for your review

**Comment by lensonp** [comment]
@Katy-katy - I just rebased this on our current release. I will review it tomorrow!

**Review by lensonp — COMMENTED** [review]
I disagree with passing this "predicted" dataframe around as an argument during training. Even though it does technically work, it is very difficult to follow logically, it adds complication to the model.train() and model.run_cross_validation() functions, and there is ultimately no reason to do it this way. The "predicted" dataframe can be handled entirely within the train_classification_models() function. All we need to do is return the cross-validation results from the model.run_cross_validation() function.

**Review by lensonp — APPROVED** [review]
with #215 merged, this is good to go

**Pull request merged**
