### PR TITLE
Examples

### PR DESCRIPTION
**Pull request by Katy-katy**

### CODE REVIEW

**Comment by lensonp** [comment]
Since this includes #31 and #30, I closed those. There is some work to do before this merges. Can you check out why it's failing tests?

**Comment by lensonp** [comment]
We have some work to do, here. Since this PR includes also #30 and #31, I will go ahead an close those two.

**Comment by lensonp** [comment]
when I open demo_using_saxskit_models_for_predictions.ipynb in my local jupyter notebook, it crashes with 
"Notebook JSON is invalid: 'execution_count' is a required property"

Apparently, this should go away if you re-run all the lines of the notebook and re-save it. Can you do that?

**Comment by lensonp** [comment]
I cleaned up one of the notebooks to my satisfaction- take a look. Mostly just details, style, and clarity are needed. I will also do the rest, but am still unable to open demo_using_saxskit_models_for_predictions.ipynb in my notebook.

**Comment by lensonp** [comment]
@Katy-katy- you force pushed. By doing that, my commit was removed.

**Comment by lensonp** [comment]
@Katy-katy you also committed checkpoint files. I'm going to re-do these commits without the checkpoint files, and separate them between the bugfix and the notebook updates. Make sure to fetch and then reset your branch instead of force pushing.

**Comment by lensonp** [comment]
@Katy-katy 

Take a look at the predict_using_saxskit and predict_using_citrination_models- both notebooks now use the same api for their models. Also see the changes to saxs_citrination.py and saxs_regression.py to support that api.

A few requests:
1. Make the sklearn-based models return uncertainty, like the citrination models.

2. Go through the other notebooks with attention to the api- try to make it sort of unified and intuitive. Imagine you are a first-time user executing the notebook and deciding if you want to use this code. If you need to make api changes, make them in a separate branch, and merge it into this one.

3. Take another swing at the README. The example script is ok, but not appealing to a prospective developer. Instead, show some simple api calls and their return results, like a simpler version of one of the "examples" notebooks.

**Comment by lensonp** [comment]
@Katy-katy the README is looking much better. There is a way to pretty-print the dictionaries- we should use it here. See https://docs.python.org/3/library/pprint.html

**Comment by lensonp** [comment]
@Katy-katy - please take a look at the TODO notes that I added in the last commit, for spherical_normal_saxs_benchmark. Note that I chose a finer resolution (0.1 instead of 0.25) because i was finding artifacts in my data with the 0.25 sampling.

**Comment by lensonp** [comment]
@Katy-katy - I just finished cleaning up the train_models notebook. Again, see the TODO tags and fill them in. This one does not need much work.

**Comment by lensonp** [comment]
@Katy-katy - The update_models notebook has two TODO items. Instead of re-training at the end, we should load the current set of models at the start, and then compare them to the updated models and use the preferred set.

Also, when running the notebook, it seems that the partial training methods have some bugs. Please fix these bugs in a separate branch and submit a PR.

**Comment by lensonp** [comment]
@Katy-katy - We are almost done with this PR. I just finished cleaning up the commit history and rebasing the branch. 

Reset your branch, and make sure that all of the notebooks are working the way you expect them to work. 

Make sure that you didn't lose any of your off-branch edits. Some notebook edits were wiped out during the rebase, so you may have to dig them out of your local copy.

Let me know when you are done. Check them carefully. Be picky, take your time, and pay attention to details. If something doesn't look right (or could look better), change it. If you need to make changes to core modules, do it in another branch. 

When you are done, I will review the notebooks one more time, and then we can merge and close this.

**Comment by Katy-katy** [comment]
I rebased examples branch of dev branch and "force pushed" it. Now I am going to update our examples notebooks and examples python scripts.

**Comment by Katy-katy** [comment]
I rebased examples branch of dev branch again and "force pushed" it. Now I am going to update our examples notebooks and examples python scripts.

**Pull request merged**
